// @ts-check
// Centralized DOM element cache.
//
// This file replaces the scattered `document.getElementById(...)` calls
// that used to appear inside individual render functions in app.js.
// All UI modules should import `els` from here. New element references
// belong in this object - not in deep render functions - so we can audit
// the DOM surface in one place.
//
// Looked up at module load. Importing this file in a non-DOM environment
// (e.g. node --test) will throw because document is undefined; that is by
// design - tests should import pure-logic modules (resolution-rules.js,
// pool.js, data.js) that do not touch the DOM.

/**
 * Required shell elements fail fast with a useful error instead of causing
 * a distant null dereference during UI initialization.
 * @template {HTMLElement} T
 * @param {string} id
 * @param {new (...args: any[]) => T} ElementType
 * @returns {T}
 */
function requiredElement(id, ElementType) {
    const element = document.getElementById(id);
    if (!(element instanceof ElementType)) throw new Error(`Missing or invalid required element #${id}`);
    return element;
}

export const els = {
    charName: requiredElement('char-name', HTMLInputElement),
    valXpEarned: requiredElement('val-xp-earned', HTMLInputElement),
    valXpSpent: requiredElement('val-xp-spent', HTMLElement),
    valStoryPointsSpent: requiredElement('val-story-points-spent', HTMLInputElement),
    valStoryPointsEarned: requiredElement('val-story-points-earned', HTMLInputElement),
    counterStepButtons: /** @type {NodeListOf<HTMLButtonElement>} */ (document.querySelectorAll('.btn-counter-step')),
    valHp: requiredElement('val-hp', HTMLInputElement),
    valHpMax: requiredElement('val-hp-max', HTMLElement),
    hpTempBadge: requiredElement('hp-temp-badge', HTMLElement),
    valEn: requiredElement('val-en', HTMLInputElement),
    valEnMax: requiredElement('val-en-max', HTMLElement),
    enTempBadge: requiredElement('en-temp-badge', HTMLElement),
    valRx: requiredElement('val-rx', HTMLInputElement),
    valRxMax: requiredElement('val-rx-max', HTMLElement),
    rxTempBadge: requiredElement('rx-temp-badge', HTMLElement),
    valSh: requiredElement('val-sh', HTMLInputElement),
    valShMax: requiredElement('val-sh-max', HTMLElement),
    shTempBadge: requiredElement('sh-temp-badge', HTMLElement),
    valArmorSoak: requiredElement('val-armor-soak', HTMLElement),
    armorSoakDetail: requiredElement('armor-soak-detail', HTMLElement),
    vitalStepButtons: /** @type {NodeListOf<HTMLButtonElement>} */ (document.querySelectorAll('.btn-vital-step')),
    shadowPool: document.getElementById('shadow-pool'),
    valAberration: requiredElement('val-aberration', HTMLInputElement),
    shadowAlignmentDisplay: requiredElement('shadow-alignment-display', HTMLElement),
    shadowAbilitiesDisplay: requiredElement('shadow-abilities-display', HTMLElement),
    shadowPanelBody: requiredElement('shadow-panel-body', HTMLElement),
    btnShadowToggle: requiredElement('btn-shadow-toggle', HTMLButtonElement),
    btnShadowInfo: requiredElement('btn-shadow-info', HTMLButtonElement),
    shadowInfoModal: requiredElement('shadow-info-modal', HTMLElement),
    btnShadowInfoClose: requiredElement('btn-shadow-info-close', HTMLButtonElement),
    btnRest: requiredElement('btn-rest', HTMLButtonElement),
    btnNewChar: requiredElement('btn-new-char', HTMLButtonElement),
    btnCalcXp: requiredElement('btn-calc-xp', HTMLButtonElement),
    btnCalcVitals: requiredElement('btn-calc-vitals', HTMLButtonElement),
    toggleOptionalStats: /** @type {HTMLInputElement|null} */ (document.getElementById('toggle-optional-stats')),
    toggleGmOverride: requiredElement('toggle-gm-override', HTMLInputElement),
    rulesReviewStrip: requiredElement('rules-review-strip', HTMLElement),
    tabStoryBadge: document.getElementById('tab-story-badge'),
    statsSummary: requiredElement('stats-summary', HTMLElement),
    btnStatsToggle: requiredElement('btn-stats-toggle', HTMLButtonElement),
    statsPanelBody: requiredElement('stats-panel-body', HTMLElement),
    statSelects: /** @type {NodeListOf<HTMLInputElement>} */ (document.querySelectorAll('.stat-select')),
    statDiceButtons: /** @type {NodeListOf<HTMLButtonElement>} */ (document.querySelectorAll('.btn-edit-stat-dice')),
    statDiceModal: requiredElement('stat-dice-modal', HTMLElement),
    statDiceModalTitle: requiredElement('stat-dice-modal-title', HTMLElement),
    statDiceModalKey: requiredElement('stat-dice-modal-key', HTMLInputElement),
    statDiceInput: requiredElement('stat-dice-input', HTMLInputElement),
    statDiceSelected: requiredElement('stat-dice-selected', HTMLElement),
    statDiceButtonsGrid: requiredElement('stat-dice-buttons', HTMLElement),
    btnStatDiceClear: requiredElement('btn-stat-dice-clear', HTMLButtonElement),
    btnStatDiceCancel: requiredElement('btn-stat-dice-cancel', HTMLButtonElement),
    btnStatDiceSave: requiredElement('btn-stat-dice-save', HTMLButtonElement),
    optionalStatBoxes: /** @type {NodeListOf<HTMLElement>} */ (document.querySelectorAll('.optional-stat')),
    cardContainer: requiredElement('card-container', HTMLDivElement),
    btnAddTile: requiredElement('btn-add-tile', HTMLButtonElement),
    charRosterList: requiredElement('char-roster-list', HTMLDivElement),
    btnDelChar: document.getElementById('btn-del-char'),
    searchTiles: requiredElement('search-tiles', HTMLInputElement),
    btnReorderTiles: requiredElement('btn-reorder-tiles', HTMLButtonElement),
    sortTilesBy: requiredElement('sort-tiles-by', HTMLSelectElement),
    btnSortDir: requiredElement('btn-sort-dir', HTMLButtonElement),
    modal: requiredElement('tile-modal', HTMLElement),
    form: requiredElement('tile-form', HTMLFormElement),
    btnCancel: requiredElement('btn-modal-cancel', HTMLButtonElement),
    btnDelete: requiredElement('btn-modal-delete', HTMLButtonElement),

    tagSelect: requiredElement('tag-select', HTMLSelectElement),
    tagCustomInput: requiredElement('tag-custom-input', HTMLInputElement),
    btnAddTag: requiredElement('btn-add-tag', HTMLButtonElement),
    tagsContainer: requiredElement('selected-tags-container', HTMLElement),
    tileDice: requiredElement('tile-dice', HTMLInputElement),
    tileDiceSelected: requiredElement('tile-dice-selected', HTMLElement),
    tileDiceButtons: requiredElement('tile-dice-buttons', HTMLElement),
    tileTagLimitStatus: requiredElement('tile-tag-limit-status', HTMLElement),

    tileXp: requiredElement('tile-xp', HTMLInputElement),
    btnEstimateXp: requiredElement('btn-estimate-xp', HTMLButtonElement),
    tileXpEstimateNote: requiredElement('tile-xp-estimate-note', HTMLElement),

    callColor1: requiredElement('call-color-1', HTMLSelectElement),
    callColor2: requiredElement('call-color-2', HTMLSelectElement),
    callColorOptions: /** @type {NodeListOf<HTMLButtonElement>} */ (document.querySelectorAll('.call-color-option')),
    callColorWarning: document.getElementById('call-color-warning'),
    btnClearCall: document.getElementById('btn-clear-call'),
    optionalCallOptions: /** @type {NodeListOf<HTMLInputElement>} */ (document.querySelectorAll('.optional-call-option')),
    autoFilterCall: requiredElement('auto-filter-call', HTMLInputElement),
    poolDiceDisplay: requiredElement('pool-dice-display', HTMLElement),
    poolAddsDisplay: requiredElement('pool-adds-display', HTMLElement),
    chainPanel: requiredElement('chain-panel', HTMLElement),
    chainOptions: requiredElement('chain-options', HTMLElement),
    tagBonusPanel: requiredElement('tag-bonus-panel', HTMLElement),
    tagBonusOptions: requiredElement('tag-bonus-options', HTMLElement),

    callTileZone: requiredElement('call-tile-container', HTMLElement),
    burnTilesZone: requiredElement('burn-tiles-container', HTMLElement),
    btnPickCallTile: requiredElement('btn-pick-call-tile', HTMLButtonElement),
    btnPickBurnTiles: requiredElement('btn-pick-burn-tiles', HTMLButtonElement),
    poolTilePickerModal: requiredElement('pool-tile-picker-modal', HTMLElement),
    poolTilePickerTitle: requiredElement('pool-tile-picker-title', HTMLElement),
    poolTilePickerHelp: requiredElement('pool-tile-picker-help', HTMLElement),
    poolTilePickerColors: requiredElement('pool-tile-picker-colors', HTMLElement),
    poolTilePickerChoices: requiredElement('pool-tile-picker-choices', HTMLElement),
    poolTilePickerEmpty: requiredElement('pool-tile-picker-empty', HTMLElement),
    btnPoolTilePickerClose: requiredElement('btn-pool-tile-picker-close', HTMLButtonElement),

    poolAssistantPanel: requiredElement('pool-assistant-panel', HTMLElement),
    poolAssistantForm: requiredElement('pool-assistant-form', HTMLFormElement),
    poolAssistantCommand: requiredElement('pool-assistant-command', HTMLInputElement),
    btnPoolAssistantMic: requiredElement('btn-pool-assistant-mic', HTMLButtonElement),
    btnPoolAssistantSuggest: requiredElement('btn-pool-assistant-suggest', HTMLButtonElement),
    poolAssistantStatus: requiredElement('pool-assistant-status', HTMLElement),
    poolAssistantPreviewModal: requiredElement('pool-assistant-preview-modal', HTMLElement),
    poolAssistantPreviewConfidence: requiredElement('pool-assistant-preview-confidence', HTMLElement),
    poolAssistantPreviewTranscript: requiredElement('pool-assistant-preview-transcript', HTMLElement),
    poolAssistantPreviewSelection: requiredElement('pool-assistant-preview-selection', HTMLElement),
    poolAssistantPreviewColors: requiredElement('pool-assistant-preview-colors', HTMLElement),
    poolAssistantPreviewCallTile: requiredElement('pool-assistant-preview-call-tile', HTMLElement),
    poolAssistantPreviewBurnTiles: requiredElement('pool-assistant-preview-burn-tiles', HTMLElement),
    poolAssistantPreviewClarification: requiredElement('pool-assistant-preview-clarification', HTMLElement),
    poolAssistantPreviewRationale: requiredElement('pool-assistant-preview-rationale', HTMLElement),
    poolAssistantPreviewWarnings: requiredElement('pool-assistant-preview-warnings', HTMLElement),
    btnPoolAssistantPreviewClose: requiredElement('btn-pool-assistant-preview-close', HTMLButtonElement),
    btnPoolAssistantCancel: requiredElement('btn-pool-assistant-cancel', HTMLButtonElement),
    btnPoolAssistantApply: requiredElement('btn-pool-assistant-apply', HTMLButtonElement),

    radioModes: /** @type {NodeListOf<HTMLInputElement>} */ (document.querySelectorAll('input[name="roll-mode"]')),
    testRollToggle: requiredElement('test-roll-toggle', HTMLInputElement),
    virtualSection: requiredElement('virtual-roll-section', HTMLElement),
    manualSection: requiredElement('manual-roll-section', HTMLElement),
    btnRoll: requiredElement('btn-roll', HTMLButtonElement),
    btnCalculate: requiredElement('btn-calculate', HTMLButtonElement),
    manualInputsContainer: requiredElement('manual-inputs-container', HTMLElement),
    extraDiceInput: requiredElement('extra-dice-input', HTMLInputElement),
    extraDiceSelected: requiredElement('extra-dice-selected', HTMLElement),
    extraDiceButtons: requiredElement('extra-dice-buttons', HTMLElement),
    risenAberrantEffect: requiredElement('risen-aberrant-effect', HTMLInputElement),
    fallenAberrantEffect: requiredElement('fallen-aberrant-effect', HTMLInputElement),
    freebieDieSelect: requiredElement('freebie-die-select', HTMLSelectElement),
    freebieDieButtons: requiredElement('freebie-die-buttons', HTMLElement),

    corePanel: requiredElement('core-panel', HTMLElement),
    coreDisplay: requiredElement('core-display', HTMLElement),
    btnCoreToggle: requiredElement('btn-core-toggle', HTMLButtonElement),
    corePanelBody: requiredElement('core-panel-body', HTMLElement),
    valCore: requiredElement('val-core', HTMLInputElement),
    coreAbilities: requiredElement('core-abilities', HTMLElement),

    strangerPanel: requiredElement('stranger-panel', HTMLElement),
    strangerSummary: requiredElement('stranger-summary', HTMLElement),
    btnStrangerToggle: requiredElement('btn-stranger-toggle', HTMLButtonElement),
    strangerPanelBody: requiredElement('stranger-panel-body', HTMLElement),
    strangerFormSection: requiredElement('stranger-form-section', HTMLElement),
    strangerFormSelect: requiredElement('stranger-form-select', HTMLSelectElement),
    strangerFormDetail: requiredElement('stranger-form-detail', HTMLElement),
    strangerCelestialSection: requiredElement('stranger-celestial-section', HTMLElement),
    celestialAspectSelect: requiredElement('celestial-aspect-select', HTMLSelectElement),
    celestialAspectDetail: requiredElement('celestial-aspect-detail', HTMLElement),
    strangerBestialNote: requiredElement('stranger-bestial-note', HTMLElement),

    titanPanel: requiredElement('titan-panel', HTMLElement),
    titanDisplay: requiredElement('titan-display', HTMLElement),
    btnTitanToggle: requiredElement('btn-titan-toggle', HTMLButtonElement),
    titanPanelBody: requiredElement('titan-panel-body', HTMLElement),
    valTitan: requiredElement('val-titan', HTMLInputElement),
    titanHvTracker: requiredElement('titan-hv-tracker', HTMLElement),
    titanAbilities: requiredElement('titan-abilities', HTMLElement),

    btnNpcToggle: requiredElement('btn-npc-toggle', HTMLButtonElement),
    npcPanelBody: requiredElement('npc-panel-body', HTMLElement),
    npcList: requiredElement('npc-list', HTMLElement),

    statusConditionsDisplay: requiredElement('status-conditions-display', HTMLElement),
    btnConditionToggle: requiredElement('btn-condition-toggle', HTMLButtonElement),
    conditionPanelBody: requiredElement('condition-panel-body', HTMLElement),
    critsDashboard: requiredElement('crits-dashboard', HTMLElement),
    pressTracker: requiredElement('press-tracker', HTMLElement),

    rollResults: requiredElement('roll-results', HTMLElement),
    resultNotices: requiredElement('result-notices', HTMLElement),
    resultTotal: requiredElement('result-total', HTMLElement),
    resolutionControls: requiredElement('resolution-controls', HTMLElement),
    resultDetails: requiredElement('result-details', HTMLElement),

    btnExport: requiredElement('btn-export', HTMLButtonElement),
    fileImport: requiredElement('file-import', HTMLInputElement),

    // Vital Modal
    vitalModal: requiredElement('vital-modal', HTMLElement),
    vitalModalTitle: requiredElement('vital-modal-title', HTMLElement),
    vitalModalKey: requiredElement('vital-modal-key', HTMLInputElement),
    vitalPermInput: requiredElement('vital-perm-input', HTMLInputElement),
    vitalTempInput: requiredElement('vital-temp-input', HTMLInputElement),
    btnVitalCancel: requiredElement('btn-vital-cancel', HTMLButtonElement),
    btnVitalSave: requiredElement('btn-vital-save', HTMLButtonElement),

    // Journal
    btnAddJournal: requiredElement('btn-add-journal', HTMLButtonElement),
    journalContainer: requiredElement('journal-entries-container', HTMLElement),

    // Info
    btnInfo: requiredElement('btn-info', HTMLButtonElement),
    infoModal: requiredElement('info-modal', HTMLElement),
    btnInfoClose: requiredElement('btn-info-close', HTMLButtonElement),

    // Storage-error banner (surfaced by js/ui/notifications.js when
    // data.js dispatches a 'storage-error' CustomEvent).
    storageErrorBanner: requiredElement('storage-error-banner', HTMLElement),
    storageErrorBannerDetail: requiredElement('storage-error-banner-detail', HTMLElement),
    btnStorageErrorDismiss: requiredElement('btn-storage-error-dismiss', HTMLButtonElement),
    btnStorageErrorExport: requiredElement('btn-storage-error-export', HTMLButtonElement),

    cloudPanel: document.getElementById('cloud-panel'),
    btnCloudToggle: requiredElement('btn-cloud-toggle', HTMLButtonElement),
    cloudPanelBody: requiredElement('cloud-panel-body', HTMLElement),
    cloudModeLabel: document.getElementById('cloud-mode-label'),
    cloudStatusText: document.getElementById('cloud-status-text'),
    authForm: requiredElement('auth-form', HTMLFormElement),
    btnAuthGoogle: requiredElement('btn-auth-google', HTMLButtonElement),
    authEmail: requiredElement('auth-email', HTMLInputElement),
    btnAuthSendLink: requiredElement('btn-auth-send-link', HTMLButtonElement),
    btnAuthSignOut: requiredElement('btn-auth-sign-out', HTMLButtonElement),
    authCodeForm: requiredElement('auth-code-form', HTMLFormElement),
    authCode: requiredElement('auth-code', HTMLInputElement),
    btnAuthVerifyCode: requiredElement('btn-auth-verify-code', HTMLButtonElement),
    cloudActions: document.getElementById('cloud-actions'),
    btnUploadLocal: requiredElement('btn-upload-local', HTMLButtonElement),
    campaignNameInput: requiredElement('campaign-name-input', HTMLInputElement),
    btnCreateCampaign: requiredElement('btn-create-campaign', HTMLButtonElement),
    campaignCodeInput: requiredElement('campaign-code-input', HTMLInputElement),
    btnJoinCampaign: requiredElement('btn-join-campaign', HTMLButtonElement),
    campaignPanel: document.getElementById('campaign-panel'),
    campaignSignedOutNote: document.getElementById('campaign-signed-out-note'),
    characterCampaignSelect: requiredElement('character-campaign-select', HTMLSelectElement),
    campaignManageSelect: requiredElement('campaign-manage-select', HTMLSelectElement),
    campaignMemberList: requiredElement('campaign-member-list', HTMLDivElement),
    rollLogList: requiredElement('roll-log-list', HTMLDivElement),
    campaignFilesPanel: requiredElement('campaign-files-panel', HTMLDivElement),
    campaignFilesStatus: requiredElement('campaign-files-status', HTMLElement),
    campaignFileInput: requiredElement('campaign-file-input', HTMLInputElement),
    campaignFileTitle: requiredElement('campaign-file-title', HTMLInputElement),
    btnCampaignFileUpload: requiredElement('btn-campaign-file-upload', HTMLButtonElement),
    campaignFileList: requiredElement('campaign-file-list', HTMLDivElement),
    campaignAiDocsPanel: requiredElement('campaign-ai-docs-panel', HTMLElement),
    campaignAiDocsStatus: requiredElement('campaign-ai-docs-status', HTMLElement),
    campaignAiScenarioSeed: requiredElement('campaign-ai-scenario-seed', HTMLTextAreaElement),
    campaignAiGmInstructions: requiredElement('campaign-ai-gm-instructions', HTMLTextAreaElement),
    btnCampaignAiSettingsSave: requiredElement('btn-campaign-ai-settings-save', HTMLButtonElement),
    campaignAiDocTitle: requiredElement('campaign-ai-doc-title', HTMLInputElement),
    campaignAiDocFile: requiredElement('campaign-ai-doc-file', HTMLInputElement),
    campaignAiDocText: requiredElement('campaign-ai-doc-text', HTMLTextAreaElement),
    btnCampaignAiDocUpload: requiredElement('btn-campaign-ai-doc-upload', HTMLButtonElement),
    campaignAiDocList: requiredElement('campaign-ai-doc-list', HTMLElement),
    aiCreationSection: requiredElement('ai-creation-section', HTMLElement),
    aiCreationStatus: requiredElement('ai-creation-status', HTMLElement),
    btnAiThreadStart: requiredElement('btn-ai-thread-start', HTMLButtonElement),
    btnAiSceneFinalize: requiredElement('btn-ai-scene-finalize', HTMLButtonElement),
    btnAiSceneCancel: requiredElement('btn-ai-scene-cancel', HTMLButtonElement),
    aiCreationMessages: requiredElement('ai-creation-messages', HTMLElement),
    aiCreationForm: requiredElement('ai-creation-form', HTMLFormElement),
    aiCreationInput: requiredElement('ai-creation-input', HTMLTextAreaElement),
    btnAiMessageSend: requiredElement('btn-ai-message-send', HTMLButtonElement),
    aiSceneSummaryList: requiredElement('ai-scene-summary-list', HTMLElement),
    readonlyBanner: document.getElementById('readonly-banner')
};
