// Centralized DOM element cache.
//
// This file replaces the scattered `document.getElementById(...)` calls
// that used to appear inside individual render functions in app.js.
// All UI modules should import `els` from here. New element references
// belong in this object - not in deep render functions - so we can audit
// the DOM surface in one place.
//
// Looked up at module load. Importing this file in a non-DOM environment
// (e.g. node --test) will throw because document is undefined; that is by
// design - tests should import pure-logic modules (resolution-rules.js,
// pool.js, data.js) that do not touch the DOM.

export const els = {
    charName: document.getElementById('char-name'),
    valXpEarned: document.getElementById('val-xp-earned'),
    valXpSpent: document.getElementById('val-xp-spent'),
    valStoryPointsSpent: document.getElementById('val-story-points-spent'),
    valStoryPointsEarned: document.getElementById('val-story-points-earned'),
    counterStepButtons: document.querySelectorAll('.btn-counter-step'),
    valHp: document.getElementById('val-hp'),
    valHpMax: document.getElementById('val-hp-max'),
    hpTempBadge: document.getElementById('hp-temp-badge'),
    valEn: document.getElementById('val-en'),
    valEnMax: document.getElementById('val-en-max'),
    enTempBadge: document.getElementById('en-temp-badge'),
    valRx: document.getElementById('val-rx'),
    valRxMax: document.getElementById('val-rx-max'),
    rxTempBadge: document.getElementById('rx-temp-badge'),
    valSh: document.getElementById('val-sh'),
    valShMax: document.getElementById('val-sh-max'),
    shTempBadge: document.getElementById('sh-temp-badge'),
    valArmorSoak: document.getElementById('val-armor-soak'),
    armorSoakDetail: document.getElementById('armor-soak-detail'),
    vitalStepButtons: document.querySelectorAll('.btn-vital-step'),
    shadowPool: document.getElementById('shadow-pool'),
    valAberration: document.getElementById('val-aberration'),
    shadowAlignmentDisplay: document.getElementById('shadow-alignment-display'),
    shadowAbilitiesDisplay: document.getElementById('shadow-abilities-display'),
    shadowPanelBody: document.getElementById('shadow-panel-body'),
    btnShadowToggle: document.getElementById('btn-shadow-toggle'),
    btnShadowInfo: document.getElementById('btn-shadow-info'),
    shadowInfoModal: document.getElementById('shadow-info-modal'),
    btnShadowInfoClose: document.getElementById('btn-shadow-info-close'),
    btnRest: document.getElementById('btn-rest'),
    btnNewChar: document.getElementById('btn-new-char'),
    btnCalcXp: document.getElementById('btn-calc-xp'),
    btnCalcVitals: document.getElementById('btn-calc-vitals'),
    toggleOptionalStats: document.getElementById('toggle-optional-stats'),
    toggleGmOverride: document.getElementById('toggle-gm-override'),
    rulesReviewStrip: document.getElementById('rules-review-strip'),
    statSelects: document.querySelectorAll('.stat-select'),
    statDiceButtons: document.querySelectorAll('.btn-edit-stat-dice'),
    statDiceModal: document.getElementById('stat-dice-modal'),
    statDiceModalTitle: document.getElementById('stat-dice-modal-title'),
    statDiceModalKey: document.getElementById('stat-dice-modal-key'),
    statDiceInput: document.getElementById('stat-dice-input'),
    statDiceSelected: document.getElementById('stat-dice-selected'),
    statDiceButtonsGrid: document.getElementById('stat-dice-buttons'),
    btnStatDiceClear: document.getElementById('btn-stat-dice-clear'),
    btnStatDiceCancel: document.getElementById('btn-stat-dice-cancel'),
    btnStatDiceSave: document.getElementById('btn-stat-dice-save'),
    optionalStatBoxes: document.querySelectorAll('.optional-stat'),
    cardContainer: document.getElementById('card-container'),
    btnAddTile: document.getElementById('btn-add-tile'),
    charRosterSelect: document.getElementById('char-roster-select'),
    btnDelChar: document.getElementById('btn-del-char'),
    searchTiles: document.getElementById('search-tiles'),
    btnReorderTiles: document.getElementById('btn-reorder-tiles'),
    sortTilesBy: document.getElementById('sort-tiles-by'),
    btnSortDir: document.getElementById('btn-sort-dir'),
    modal: document.getElementById('tile-modal'),
    form: document.getElementById('tile-form'),
    btnCancel: document.getElementById('btn-modal-cancel'),
    btnDelete: document.getElementById('btn-modal-delete'),

    tagSelect: document.getElementById('tag-select'),
    tagCustomInput: document.getElementById('tag-custom-input'),
    btnAddTag: document.getElementById('btn-add-tag'),
    tagsContainer: document.getElementById('selected-tags-container'),
    tileDice: document.getElementById('tile-dice'),
    tileDiceSelected: document.getElementById('tile-dice-selected'),
    tileDiceButtons: document.getElementById('tile-dice-buttons'),
    tileTagLimitStatus: document.getElementById('tile-tag-limit-status'),

    tileXp: document.getElementById('tile-xp'),
    btnEstimateXp: document.getElementById('btn-estimate-xp'),
    tileXpEstimateNote: document.getElementById('tile-xp-estimate-note'),

    callColor1: document.getElementById('call-color-1'),
    callColor2: document.getElementById('call-color-2'),
    callColorOptions: document.querySelectorAll('.call-color-option'),
    callColorWarning: document.getElementById('call-color-warning'),
    btnClearCall: document.getElementById('btn-clear-call'),
    optionalCallOptions: document.querySelectorAll('.optional-call-option'),
    autoFilterCall: document.getElementById('auto-filter-call'),
    poolDiceDisplay: document.getElementById('pool-dice-display'),
    poolAddsDisplay: document.getElementById('pool-adds-display'),
    chainPanel: document.getElementById('chain-panel'),
    chainOptions: document.getElementById('chain-options'),
    tagBonusPanel: document.getElementById('tag-bonus-panel'),
    tagBonusOptions: document.getElementById('tag-bonus-options'),

    callTileZone: document.getElementById('call-tile-container'),
    burnTilesZone: document.getElementById('burn-tiles-container'),

    radioModes: document.querySelectorAll('input[name="roll-mode"]'),
    testRollToggle: document.getElementById('test-roll-toggle'),
    virtualSection: document.getElementById('virtual-roll-section'),
    manualSection: document.getElementById('manual-roll-section'),
    btnRoll: document.getElementById('btn-roll'),
    btnCalculate: document.getElementById('btn-calculate'),
    manualInputsContainer: document.getElementById('manual-inputs-container'),
    extraDiceInput: document.getElementById('extra-dice-input'),
    extraDiceSelected: document.getElementById('extra-dice-selected'),
    extraDiceButtons: document.getElementById('extra-dice-buttons'),
    risenAberrantEffect: document.getElementById('risen-aberrant-effect'),
    fallenAberrantEffect: document.getElementById('fallen-aberrant-effect'),
    freebieDieSelect: document.getElementById('freebie-die-select'),

    corePanel: document.getElementById('core-panel'),
    coreDisplay: document.getElementById('core-display'),
    btnCoreToggle: document.getElementById('btn-core-toggle'),
    corePanelBody: document.getElementById('core-panel-body'),
    valCore: document.getElementById('val-core'),
    coreAbilities: document.getElementById('core-abilities'),

    statusConditionsDisplay: document.getElementById('status-conditions-display'),
    btnConditionToggle: document.getElementById('btn-condition-toggle'),
    conditionPanelBody: document.getElementById('condition-panel-body'),
    critsDashboard: document.getElementById('crits-dashboard'),
    pressTracker: document.getElementById('press-tracker'),

    rollResults: document.getElementById('roll-results'),
    resultNotices: document.getElementById('result-notices'),
    resultTotal: document.getElementById('result-total'),
    resolutionControls: document.getElementById('resolution-controls'),
    resultDetails: document.getElementById('result-details'),

    btnExport: document.getElementById('btn-export'),
    fileImport: document.getElementById('file-import'),

    // Vital Modal
    vitalModal: document.getElementById('vital-modal'),
    vitalModalTitle: document.getElementById('vital-modal-title'),
    vitalModalKey: document.getElementById('vital-modal-key'),
    vitalPermInput: document.getElementById('vital-perm-input'),
    vitalTempInput: document.getElementById('vital-temp-input'),
    btnVitalCancel: document.getElementById('btn-vital-cancel'),
    btnVitalSave: document.getElementById('btn-vital-save'),

    // Journal
    btnAddJournal: document.getElementById('btn-add-journal'),
    journalContainer: document.getElementById('journal-entries-container'),

    // Info
    btnInfo: document.getElementById('btn-info'),
    infoModal: document.getElementById('info-modal'),
    btnInfoClose: document.getElementById('btn-info-close'),

    // Storage-error banner (surfaced by js/ui/notifications.js when
    // data.js dispatches a 'storage-error' CustomEvent).
    storageErrorBanner: document.getElementById('storage-error-banner'),
    storageErrorBannerDetail: document.getElementById('storage-error-banner-detail'),
    btnStorageErrorDismiss: document.getElementById('btn-storage-error-dismiss'),
    btnStorageErrorExport: document.getElementById('btn-storage-error-export'),

    cloudPanel: document.getElementById('cloud-panel'),
    cloudModeLabel: document.getElementById('cloud-mode-label'),
    cloudStatusText: document.getElementById('cloud-status-text'),
    authForm: document.getElementById('auth-form'),
    authEmail: document.getElementById('auth-email'),
    btnAuthSendLink: document.getElementById('btn-auth-send-link'),
    btnAuthSignOut: document.getElementById('btn-auth-sign-out'),
    cloudActions: document.getElementById('cloud-actions'),
    btnUploadLocal: document.getElementById('btn-upload-local'),
    campaignNameInput: document.getElementById('campaign-name-input'),
    btnCreateCampaign: document.getElementById('btn-create-campaign'),
    campaignCodeInput: document.getElementById('campaign-code-input'),
    btnJoinCampaign: document.getElementById('btn-join-campaign'),
    campaignPanel: document.getElementById('campaign-panel'),
    characterCampaignSelect: document.getElementById('character-campaign-select'),
    campaignManageSelect: document.getElementById('campaign-manage-select'),
    campaignMemberList: document.getElementById('campaign-member-list'),
    rollLogList: document.getElementById('roll-log-list'),
    campaignAiDocsPanel: document.getElementById('campaign-ai-docs-panel'),
    campaignAiDocsStatus: document.getElementById('campaign-ai-docs-status'),
    campaignAiScenarioSeed: document.getElementById('campaign-ai-scenario-seed'),
    campaignAiGmInstructions: document.getElementById('campaign-ai-gm-instructions'),
    btnCampaignAiSettingsSave: document.getElementById('btn-campaign-ai-settings-save'),
    campaignAiDocTitle: document.getElementById('campaign-ai-doc-title'),
    campaignAiDocFile: document.getElementById('campaign-ai-doc-file'),
    campaignAiDocText: document.getElementById('campaign-ai-doc-text'),
    btnCampaignAiDocUpload: document.getElementById('btn-campaign-ai-doc-upload'),
    campaignAiDocList: document.getElementById('campaign-ai-doc-list'),
    aiCreationSection: document.getElementById('ai-creation-section'),
    aiCreationStatus: document.getElementById('ai-creation-status'),
    btnAiThreadStart: document.getElementById('btn-ai-thread-start'),
    btnAiSceneFinalize: document.getElementById('btn-ai-scene-finalize'),
    btnAiSceneCancel: document.getElementById('btn-ai-scene-cancel'),
    aiCreationMessages: document.getElementById('ai-creation-messages'),
    aiCreationForm: document.getElementById('ai-creation-form'),
    aiCreationInput: document.getElementById('ai-creation-input'),
    btnAiMessageSend: document.getElementById('btn-ai-message-send'),
    aiSceneSummaryList: document.getElementById('ai-scene-summary-list'),
    readonlyBanner: document.getElementById('readonly-banner')
};
